export const PROJECTS = [
   { name: "Fieldnotes", year: 2020, img: "/exp/scroll-expand/1.png" },
   { name: "Redline", year: 2021, img: "/exp/scroll-expand/2.png" },
   { name: "Gallery Walk", year: 2019, img: "/exp/scroll-expand/3.png" },
   { name: "Side Profile", year: 2022, img: "/exp/scroll-expand/4.png" },
   { name: "Open Mic", year: 2023, img: "/exp/scroll-expand/5.png" },
   { name: "Backboard", year: 2024, img: "/exp/scroll-expand/6.png" },
   { name: "Afterglow", year: 2021, img: "/exp/scroll-expand/7.png" },
   { name: "Hill House", year: 2020, img: "/exp/scroll-expand/8.png" },
   { name: "Low Tide", year: 2018, img: "/exp/scroll-expand/9.png" },
   { name: "Timepiece", year: 2019, img: "/exp/scroll-expand/10.png" },
   { name: "Close Focus", year: 2022, img: "/exp/scroll-expand/11.png" },
   { name: "Airframe", year: 2023, img: "/exp/scroll-expand/12.png" },
   { name: "Hardcase", year: 2024, img: "/exp/scroll-expand/13.png" },
   { name: "Deep Red", year: 2021, img: "/exp/scroll-expand/14.png" },
   { name: "Fast Track", year: 2022, img: "/exp/scroll-expand/15.png" },
   { name: "Night Shift", year: 2025, img: "/exp/scroll-expand/16.png" },
   { name: "Contrast Study", year: 2023, img: "/exp/scroll-expand/17.png" },
   { name: "Shoreline", year: 2022, img: "/exp/scroll-expand/18.png" },
   { name: "Raw Cut", year: 2021, img: "/exp/scroll-expand/19.png" },
   { name: "Overhead", year: 2020, img: "/exp/scroll-expand/20.png" },
   { name: "Grain & Light", year: 2019, img: "/exp/scroll-expand/21.png" },
   { name: "Thermal", year: 2024, img: "/exp/scroll-expand/22.png" },
   { name: "Wide Open", year: 2023, img: "/exp/scroll-expand/23.png" },
   { name: "Still Life", year: 2022, img: "/exp/scroll-expand/24.png" },
   { name: "Undercroft", year: 2021, img: "/exp/scroll-expand/25.png" },
   { name: "Pale Fire", year: 2020, img: "/exp/scroll-expand/26.png" },
   { name: "Exposure", year: 2019, img: "/exp/scroll-expand/27.png" },
   { name: "Blueprint", year: 2024, img: "/exp/scroll-expand/28.png" },
   { name: "Drift", year: 2023, img: "/exp/scroll-expand/29.png" },
   { name: "Monolith", year: 2022, img: "/exp/scroll-expand/30.png" },
   { name: "Long Take", year: 2021, img: "/exp/scroll-expand/31.png" },
   { name: "Residue", year: 2020, img: "/exp/scroll-expand/32.png" },
   { name: "Clearance", year: 2019, img: "/exp/scroll-expand/33.png" },
   { name: "Signal", year: 2025, img: "/exp/scroll-expand/34.png" },
];
