export const projects = [
   { title: "Glass Terrace", image: "/exp/gridscape/1.png", year: 2024 },
   { title: "Bare Concrete", image: "/exp/gridscape/2.png", year: 2023 },
   { title: "Night Bridge", image: "/exp/gridscape/3.png", year: 2025 },
   { title: "Rust Facade", image: "/exp/gridscape/4.png", year: 2023 },
   { title: "Rooftop Line", image: "/exp/gridscape/5.png", year: 2024 },
   { title: "Open Frame", image: "/exp/gridscape/6.png", year: 2022 },
   { title: "Wet Asphalt", image: "/exp/gridscape/7.png", year: 2025 },
   { title: "Split Level", image: "/exp/gridscape/8.png", year: 2023 },
   { title: "Steel Mesh", image: "/exp/gridscape/9.png", year: 2024 },
   { title: "Shadow Wall", image: "/exp/gridscape/10.png", year: 2023 },
   { title: "Grid Tower", image: "/exp/gridscape/11.png", year: 2022 },
   { title: "White Block", image: "/exp/gridscape/12.png", year: 2025 },
   { title: "Bent Surface", image: "/exp/gridscape/13.png", year: 2024 },
   { title: "Raw Beam", image: "/exp/gridscape/14.png", year: 2023 },
   { title: "Cold Light", image: "/exp/gridscape/15.png", year: 2022 },
   { title: "Void Space", image: "/exp/gridscape/16.png", year: 2024 },
   { title: "Flat Plane", image: "/exp/gridscape/17.png", year: 2023 },
   { title: "Dust Layer", image: "/exp/gridscape/18.png", year: 2025 },
   { title: "Wire Frame", image: "/exp/gridscape/19.png", year: 2023 },
   { title: "Pale Stone", image: "/exp/gridscape/20.png", year: 2024 },
   { title: "Deep Cut", image: "/exp/gridscape/21.png", year: 2022 },
   { title: "Thin Edge", image: "/exp/gridscape/22.png", year: 2023 },
   { title: "Blind Spot", image: "/exp/gridscape/23.png", year: 2025 },
   { title: "Dark Slab", image: "/exp/gridscape/24.png", year: 2022 },
];
